main: com.icloud.benjozork.chatplus.main.ChatPlus
name: ChatPlus
version: 1.3a2
author: benjozork
commands:
   cp:
      description: The main command of the plugin.
   ch:
      description: Manages chat channels.