main: ca.hotmail.benjozork.chatplus.Main.ChatPlus
name: chatPlus
version: 1.2
author: benjozork
commands:
   cp:
      description: The main command of the plugin.
      permission-message: You don't have permission for this command.